### PR TITLE
new(ci): add a sample kmod source to test that we are able to build a kmod after kernel headers are installed

### PR DESCRIPTION
**Pull request by FedeDP**

### CODE REVIEW

**Comment by FedeDP** [comment]
Draft while i test it.

**Comment by FedeDP** [comment]
Testing the action changes here: https://github.com/falcosecurity/libs/pull/1855

**Comment by FedeDP** [comment]
Once #3 is accepted, i will rebase this one to only include CI improvements so that we can further discuss them.

**Comment by FedeDP** [comment]
Rebased. As stated earlier, we need to run the CI test workflow on an actuated node because we need a vanilla kernel.
Right now the worfklow fails because of:
>  warning: Could not find remote branch v6.5.0-1018-azure to clone.
fatal: Remote branch v6.5.0-1018-azure not found in upstream origin

**Comment by alexellis** [comment]
@FedeDP could you move these tests to -> https://github.com/actuated-samples/kmod-sample

I made a repo on an org arm64 actuated servers are enabled.

**Comment by FedeDP** [comment]
Mmmh if i move the test to another repo, how can i trigger it everytime a change to `action.yml` happens here?

**Comment by alexellis** [comment]
There is no real need for that. This is a trivial action like a "macro".

I created the separate repo for you, could you move the sample over there please?

**Comment by FedeDP** [comment]
> I created the separate repo for you, could you move the sample over there please?

Yes, do you want the CI job too (eg: on push to master)?

**Pull request closed without merging**
